version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '08:30'
    open-pull-requests-limit: 50
    reviewers:
      - UltraCakeBakery
    assignees:
      - UltraCakeBakery
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
